version: '2'
services:

  mysql:
    build: mysql
    restart: always
    ports:
      - "3306:3306"
    networks:
      - backend
  php:
    build: ./
    container_name: 'php'
    restart: always
    ports:
      - '9002:9000'
    volumes:
      - ./:/var/www/symfony:cached
      - ../logs/symfony:/var/www/symfony/var/logs:cached
    depends_on:
      - "mysql"
    networks:
      - backend
  nginx:
    build: docker/nginx
    container_name: 'nginx'
    restart: always
    ports:
      - '8080:80'
    links:
      - php
    volumes_from:
      - php
    volumes:
      - ../logs/nginx/:/var/log/nginx:cached
    networks:
      - backend
networks:
    backend :
